# ============================================================
# Project: TMT Proteomics — Multi-organ Mouse Aging
# Script:  mouseTMT_insolubility_with_function.R
# Purpose: Modular reanalysis pipeline — re-runs the full
#          per-tissue analysis (normalization → ANOVA + Tukey
#          HSD → fold change → visualization) using a single
#          process_organ_data() function with organ-specific
#          labeling thresholds. Produces Soluble FC vs.
#          Insoluble FC scatter plots (both colored and
#          grey-background variants) for all 8 tissues and
#          a combined multi-organ whole-proteome plot.
#          Also computes Pearson correlations between
#          Soluble_FC and Ratio_FC per organ/comparison.
# Input:   FD_<Tissue>.xlsx (raw TMT data per organ)
# Output:  combined_plot_data_mouseTMT_<organ>.csv,
#          ratio_data_<organ>_OY/MY/OM.csv,
#          mouseTMT_<organ>_combined_facet_label*.pdf,
#          mouseTMT_multi_organ_soluble_vs_ratio*.pdf,
#          pearson_correlations_soluble_vs_ratio*.csv
# Author:  Chia-Lung Chuang
# Updated: 2026-03
# NOTE:    This script is a function-based refactor of the
#          per-tissue scripts in 01_per-tissue-analysis/.
#          It produces additional Soluble vs. Insoluble FC
#          plots not generated by the original tissue scripts.
# ============================================================

library(tidyverse)
library(ggplot2)
library(readxl)
library(ggrepel)
library(broom)
library(scales)
library(ggpmisc)

# NOTE: Set your working directory to the folder containing FD_*.xlsx files
# setwd("path/to/your/data")

# ============================================================
# 1. Organ-Specific Labeling Threshold Configuration
# ============================================================
# Thresholds define which proteins receive gene labels on plots.
# Labels appear when Soluble_FC or Insoluble_FC exceeds these bounds.

thresholds_config <- list(
  default = list(
    "Old vs. Young"    = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Old vs. Middle"   = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8)
  ),
  TA = list(
    "Old vs. Young"    = list(soluble_high = 2.0, insoluble_high = 1.2, soluble_low = -1.5, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 2.0, insoluble_high = 1.2, soluble_low = -1.0, insoluble_low = -0.8),
    "Old vs. Middle"   = list(soluble_high = 1.8, insoluble_high = 0.7, soluble_low = -0.6, insoluble_low = -1.2)
  ),
  He = list(
    "Old vs. Young"    = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -0.5, insoluble_low = -0.5),
    "Old vs. Middle"   = list(soluble_high = 1.0, insoluble_high = 0.7, soluble_low = -0.5, insoluble_low = -0.5)
  ),
  CB = list(
    "Old vs. Young"    = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 0.9, insoluble_high = 1.0, soluble_low = -0.7, insoluble_low = -1.0),
    "Old vs. Middle"   = list(soluble_high = 0.5, insoluble_high = 0.8, soluble_low = -0.3, insoluble_low = -0.5)
  ),
  HC = list(
    "Old vs. Young"    = list(soluble_high = 1.5, insoluble_high = 1.5, soluble_low = -1.0, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 1.0, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.4),
    "Old vs. Middle"   = list(soluble_high = 1.0, insoluble_high = 0.8, soluble_low = -0.8, insoluble_low = -0.6)
  ),
  NC = list(
    "Old vs. Young"    = list(soluble_high = 2.0, insoluble_high = 2.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 1.0, insoluble_high = 1.2, soluble_low = -1.0, insoluble_low = -0.8),
    "Old vs. Middle"   = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8)
  ),
  So = list(
    "Old vs. Young"    = list(soluble_high = 1.3, insoluble_high = 1.6, soluble_low = -1.2, insoluble_low = -0.8),
    "Middle vs. Young" = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Old vs. Middle"   = list(soluble_high = 1.2, insoluble_high = 0.7, soluble_low = -0.8, insoluble_low = -0.7)
  ),
  Li = list(
    "Old vs. Young"    = list(soluble_high = 1.4, insoluble_high = 1.6, soluble_low = -1.3, insoluble_low = -1.5),
    "Middle vs. Young" = list(soluble_high = 0.8, insoluble_high = 0.8, soluble_low = -1.3, insoluble_low = -2.0),
    "Old vs. Middle"   = list(soluble_high = 1.0, insoluble_high = 1.0, soluble_low = -0.8, insoluble_low = -0.5)
  ),
  WAT = list(
    "Old vs. Young"    = list(soluble_high = 1.2, insoluble_high = 2.5, soluble_low = -1.2, insoluble_low = -1.3),
    "Middle vs. Young" = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8),
    "Old vs. Middle"   = list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8)
  )
)

# Returns the threshold list for a given organ × comparison combination
get_thresholds <- function(organ_code, comparison) {
  if (organ_code %in% names(thresholds_config) &&
      comparison %in% names(thresholds_config[[organ_code]])) {
    return(thresholds_config[[organ_code]][[comparison]])
  } else if (comparison %in% names(thresholds_config$default)) {
    return(thresholds_config$default[[comparison]])
  }
  return(list(soluble_high = 1.2, insoluble_high = 1.0, soluble_low = -1.0, insoluble_low = -0.8))
}

# ============================================================
# 2. Input File Map
# ============================================================

organ_files <- list(
  TA  = "FD_Tibialis Anterior.xlsx",
  He  = "FD_Heart.xlsx",
  CB  = "FD_Cerebellum.xlsx",
  HC  = "FD_Hippocampus.xlsx",
  NC  = "FD_Neocortex.xlsx",
  So  = "FD_Soleus.xlsx",
  Li  = "FD_Liver.xlsx",
  WAT = "FD_White adipose tissue.xlsx"
)

organ_name_map <- c(
  TA  = "Tibialis Anterior", He  = "Heart",
  CB  = "Cerebellum",        HC  = "Hippocampus",
  NC  = "Neocortex",         So  = "Soleus",
  Li  = "Liver",             WAT = "White Adipose Tissue"
)

# Column name regex for each tissue (parses TMT channel names)
pattern_map <- list(
  CB  = "sig\\d+[NC]?\\.\\.[Cc]er_(\\d+M)(\\d+)_([SI])",
  He  = "sig\\d+[NC]?\\.\\.[Hh]ea_(\\d+M)(\\d+)_([SI])",
  HC  = "sig\\d+[NC]?\\.\\.[Hh]ip_(\\d+M)(\\d+)_([SI])",
  Li  = "sig\\d+[NC]?\\.\\.[Ll]iv_(\\d+M)(\\d+)_([SI])",
  NC  = "sig\\d+[NC]?\\.\\.[Nn]eo_(\\d+M)(\\d+)_([SI])",
  So  = "sig\\d+[NC]?\\.\\.[Ss]ol_(\\d+M)(\\d+)_([SI])",
  TA  = "sig\\d+[NC]?\\.\\.[Tt][Aa]_(\\d+M)(\\d+)_([SI])",
  WAT = "sig\\d+[NC]?\\.\\.[Ww]at_(\\d+M)(\\d+)_([SI])"
)

# ============================================================
# 3. Main Per-Tissue Processing Function
# ============================================================

process_organ_data <- function(organ_code, file_path) {
  cat("\n====", organ_code, "====\n")
  
  # --- 3a. Data import and cleaning ---
  data <- read_excel(file_path)
  write.csv(data, paste0("FD_", organ_code, ".csv"), row.names = FALSE)
  data_org <- read.csv(paste0("FD_", organ_code, ".csv")) %>%
    mutate(Protein.ID_cleaned = sub("_DROME$", "", Protein.Accession..),
           GN_ID = paste(GN, Protein.ID_cleaned, sep = "_"))
  write.csv(data_org, paste0("data_mouse_", organ_code, ".csv"), row.names = FALSE)
  
  # --- 3b. Reshape to long format ---
  normalize_replicates <- function(df) {
    df %>%
      group_by(Age, Solubility) %>%
      mutate(Replicate = as.integer((dense_rank(Replicate) - 1) %% 3 + 1)) %>%
      ungroup()
  }
  
  data_org_long <- data_org %>%
    pivot_longer(cols = starts_with("sig"),
                 names_to = c("Age", "Replicate", "Solubility"),
                 names_pattern = pattern_map[[organ_code]],
                 values_to = "Measurement") %>%
    mutate(Age = case_when(Age == "6M" ~ "Young", Age == "24M" ~ "Middle", Age == "30M" ~ "Old"),
           Solubility = case_when(Solubility == "S" ~ "Soluble", Solubility == "I" ~ "Insoluble"),
           Replicate = as.integer(Replicate), Measurement = as.numeric(Measurement)) %>%
    normalize_replicates()
  
  data_org_wider <- data_org_long %>%
    pivot_wider(names_from = Solubility, values_from = Measurement,
                id_cols = c(Age, GN, GN_ID, Replicate)) %>%
    mutate(Ratio = Insoluble / Soluble, Abundance = Soluble + Insoluble)
  
  # --- 3c. ANOVA + Tukey HSD for Ratio, Abundance, Soluble, Insoluble ---
  run_tukey <- function(df, response) {
    formula <- as.formula(paste(response, "~ Age"))
    anova_res <- df %>% group_by(GN_ID) %>%
      do(aov_result = aov(formula, data = .)) %>% ungroup()
    
    tukey_res <- anova_res %>%
      mutate(tukey_result = map(aov_result, ~ tidy(TukeyHSD(.)))) %>%
      unnest(tukey_result) %>%
      select(GN_ID, comparison = contrast, p.value = adj.p.value) %>%
      pivot_wider(names_from = comparison, values_from = p.value, names_prefix = "p.value_") %>%
      rename_with(~ gsub("p.value_Young-Middle", paste0(substr(response,1,2), ".p.value_middle_young"), .),
                  starts_with("p.value_Young-Middle")) %>%
      rename_with(~ gsub("p.value_Old-Middle",  paste0(substr(response,1,2), ".p.value_old_middle"),   .),
                  starts_with("p.value_Old-Middle")) %>%
      rename_with(~ gsub("p.value_Young-Old",   paste0(substr(response,1,2), ".p.value_old_young"),    .),
                  starts_with("p.value_Young-Old"))
    return(tukey_res)
  }
  
  tukey_ra  <- run_tukey(data_org_wider, "Ratio")
  tukey_ab  <- run_tukey(data_org_wider, "Abundance")
  tukey_so  <- run_tukey(data_org_wider, "Soluble")
  tukey_ins <- run_tukey(data_org_wider, "Insoluble")
  
  # --- 3d. Log2 fold changes for all 3 comparisons ---
  compute_fc <- function(df, a, b, suffix) {
    df %>%
      group_by(GN_ID, GN) %>%
      summarize(
        "{suffix}_Abundance_mean_{a}" := mean(Abundance[Age == tools::toTitleCase(a)], na.rm = TRUE),
        "{suffix}_Abundance_mean_{b}" := mean(Abundance[Age == tools::toTitleCase(b)], na.rm = TRUE),
        "{suffix}_Ratio_mean_{a}"     := mean(Ratio[Age == tools::toTitleCase(a)], na.rm = TRUE),
        "{suffix}_Ratio_mean_{b}"     := mean(Ratio[Age == tools::toTitleCase(b)], na.rm = TRUE),
        "{suffix}_Soluble_mean_{a}"   := mean(Soluble[Age == tools::toTitleCase(a)], na.rm = TRUE),
        "{suffix}_Soluble_mean_{b}"   := mean(Soluble[Age == tools::toTitleCase(b)], na.rm = TRUE),
        "{suffix}_Insoluble_mean_{a}" := mean(Insoluble[Age == tools::toTitleCase(a)], na.rm = TRUE),
        "{suffix}_Insoluble_mean_{b}" := mean(Insoluble[Age == tools::toTitleCase(b)], na.rm = TRUE),
        .groups = "drop"
      )
  }
  
  # Use simpler direct approach for clarity
  fc_OY <- data_org_wider %>% group_by(GN_ID, GN) %>%
    summarize(Abundance_FC_old_young  = log2(mean(Abundance[Age=="Old"],   na.rm=T) / mean(Abundance[Age=="Young"], na.rm=T)),
              Ratio_FC_old_young      = log2(mean(Ratio[Age=="Old"],       na.rm=T) / mean(Ratio[Age=="Young"],     na.rm=T)),
              Soluble_FC_old_young    = log2(mean(Soluble[Age=="Old"],     na.rm=T) / mean(Soluble[Age=="Young"],   na.rm=T)),
              Insoluble_FC_old_young  = log2(mean(Insoluble[Age=="Old"],   na.rm=T) / mean(Insoluble[Age=="Young"], na.rm=T)),
              Abundance_mean_young    = mean(Abundance[Age=="Young"], na.rm=T), .groups="drop")
  
  fc_MY <- data_org_wider %>% group_by(GN_ID, GN) %>%
    summarize(Abundance_FC_middle_young  = log2(mean(Abundance[Age=="Middle"],  na.rm=T) / mean(Abundance[Age=="Young"], na.rm=T)),
              Ratio_FC_middle_young      = log2(mean(Ratio[Age=="Middle"],      na.rm=T) / mean(Ratio[Age=="Young"],     na.rm=T)),
              Soluble_FC_middle_young    = log2(mean(Soluble[Age=="Middle"],    na.rm=T) / mean(Soluble[Age=="Young"],   na.rm=T)),
              Insoluble_FC_middle_young  = log2(mean(Insoluble[Age=="Middle"],  na.rm=T) / mean(Insoluble[Age=="Young"], na.rm=T)),
              .groups = "drop")
  
  fc_OM <- data_org_wider %>% group_by(GN_ID, GN) %>%
    summarize(Abundance_FC_old_middle  = log2(mean(Abundance[Age=="Old"],   na.rm=T) / mean(Abundance[Age=="Middle"], na.rm=T)),
              Ratio_FC_old_middle      = log2(mean(Ratio[Age=="Old"],       na.rm=T) / mean(Ratio[Age=="Middle"],     na.rm=T)),
              Soluble_FC_old_middle    = log2(mean(Soluble[Age=="Old"],     na.rm=T) / mean(Soluble[Age=="Middle"],   na.rm=T)),
              Insoluble_FC_old_middle  = log2(mean(Insoluble[Age=="Old"],   na.rm=T) / mean(Insoluble[Age=="Middle"], na.rm=T)),
              .groups = "drop")
  
  write.csv(fc_OY, paste0("ratio_data_", organ_code, "_OY.csv"), row.names = FALSE)
  write.csv(fc_MY, paste0("ratio_data_", organ_code, "_MY.csv"), row.names = FALSE)
  write.csv(fc_OM, paste0("ratio_data_", organ_code, "_OM.csv"), row.names = FALSE)
  
  # --- 3e. Merge and build plot_data ---
  plot_data_org <- fc_OY %>%
    left_join(fc_OM, by = c("GN_ID","GN")) %>%
    left_join(fc_MY, by = c("GN_ID","GN")) %>%
    left_join(tukey_ra,  by = "GN_ID") %>%
    left_join(tukey_ab,  by = "GN_ID") %>%
    left_join(tukey_so,  by = "GN_ID") %>%
    left_join(tukey_ins, by = "GN_ID") %>%
    mutate(
      Size_ra_old_young    = ifelse(is.na(Ra.p.value_old_young),    1, -log10(Ra.p.value_old_young)),
      Size_ra_middle_young = ifelse(is.na(Ra.p.value_middle_young), 1, -log10(Ra.p.value_middle_young)),
      Size_ra_old_middle   = ifelse(is.na(Ra.p.value_old_middle),   1, -log10(Ra.p.value_old_middle))
    ) %>%
    filter(!grepl("co|CON_", GN_ID))
  
  write.csv(plot_data_org, paste0("mouseTMT_", organ_code, ".csv"), row.names = FALSE)
  
  # --- 3f. Build per-comparison combined tables ---
  make_comp_table <- function(fc_col_suffix, size_col, comp_label) {
    plot_data_org %>%
      mutate(Comparison = comp_label) %>%
      select(GN_ID, GN,
             Abundance_FC    = paste0("Abundance_FC_", fc_col_suffix),
             Ratio_FC        = paste0("Ratio_FC_",     fc_col_suffix),
             Soluble_FC      = paste0("Soluble_FC_",   fc_col_suffix),
             Insoluble_FC    = paste0("Insoluble_FC_", fc_col_suffix),
             Size            = !!sym(size_col),
             Comparison)
  }
  
  comp_OY <- make_comp_table("old_young",    "Size_ra_old_young",    "Old vs. Young")
  comp_MY <- make_comp_table("middle_young", "Size_ra_middle_young", "Middle vs. Young")
  comp_OM <- make_comp_table("old_middle",   "Size_ra_old_middle",   "Old vs. Middle")
  
  # Apply labeling thresholds
  add_labels <- function(df, comp) {
    t <- get_thresholds(organ_code, comp)
    df %>% mutate(Label = case_when(
      is.na(GN) | GN == "NA" ~ NA_character_,
      Soluble_FC > t$soluble_high | Insoluble_FC > t$insoluble_high |
        Soluble_FC < t$soluble_low  | Insoluble_FC < t$insoluble_low ~ GN,
      TRUE ~ NA_character_
    ))
  }
  
  combined_org <- bind_rows(
    add_labels(comp_OY, "Old vs. Young"),
    add_labels(comp_MY, "Middle vs. Young"),
    add_labels(comp_OM, "Old vs. Middle")
  ) %>% filter(!is.na(GN) & GN != "NA")
  
  # Grey variant — significance flag for background points
  combined_org_grey <- combined_org %>%
    mutate(is_significant = !is.na(Size) & Size >= 1.3)
  
  write.csv(combined_org %>% select(-Label),        paste0("combined_plot_data_mouseTMT_", organ_code, ".csv"),        row.names = FALSE)
  write.csv(combined_org_grey %>% select(-Label),   paste0("combined_plot_data_mouseTMT_", organ_code, "_grey.csv"),   row.names = FALSE)
  write.csv(combined_org %>% filter(!is.na(Size) & Size >= 1.3) %>% select(-Label),
            paste0("combined_plot_data_mouseTMT_", organ_code, "_filtered.csv"), row.names = FALSE)
  
  # --- 3g. Visualization ---
  full_name <- organ_name_map[organ_code]
  
  shared_theme <- theme_minimal() +
    theme(panel.spacing = unit(1.5, "lines"),
          axis.text.x   = element_text(size = 14, face = "bold"),
          axis.text.y   = element_text(size = 14, face = "bold"),
          legend.text   = element_text(size = 12, face = "italic"),
          legend.title  = element_text(size = 14, face = "bold"),
          plot.title    = element_text(size = 16, face = "bold"),
          axis.title.x  = element_text(size = 14, face = "bold"),
          axis.title.y  = element_text(size = 14, face = "bold"),
          strip.text    = element_text(size = 14, face = "bold"))
  
  comp_colors <- scale_color_manual(
    values = c("Old vs. Young" = "purple4", "Middle vs. Young" = "maroon2", "Old vs. Middle" = "darkgreen"))
  
  filtered_org <- combined_org %>% filter(!is.na(Size) & Size >= 1.3)
  
  # Colored — significant only
  p_colored <- ggplot(filtered_org, aes(x = Soluble_FC, y = Insoluble_FC, size = Size,
                                        label = Label, color = Comparison)) +
    geom_point(alpha = 0.4) +
    geom_text_repel(size = 5, fontface = "bold", segment.color = "grey50",
                    max.overlaps = Inf, nudge_x = 0.1, nudge_y = 0.1,
                    box.padding = 0.2, point.padding = 0.2, na.rm = TRUE) +
    scale_size_continuous(range = c(1,9), name = "P-Value Size (-log10)",
                          breaks = c(1.3,2,3,4,5), limit = c(1.3,6),
                          labels = c("1.30(p<0.05)","2","3","4","5")) +
    comp_colors +
    stat_poly_eq(aes(label = paste(after_stat(rr.label))), rr.digits = 3,
                 parse = TRUE, color = "black", show.legend = FALSE) +
    labs(title   = paste0("MouseTMT ", full_name, ": Soluble FC vs. Insoluble FC"),
         x       = "Log2 Soluble fold change",
         y       = "Log2 Insoluble fold change",
         caption = "Point size based on statistical significance of Age difference in insolubility.") +
    scale_x_continuous(labels = scales::label_number(accuracy = 0.1)) +
    shared_theme + facet_wrap(~Comparison) +
    guides(color = guide_legend(override.aes = list(label = "")))
  
  print(p_colored)
  ggsave(paste0("mouseTMT_", organ_code, "_combined_facet_label.pdf"),
         p_colored, width = 7200, height = 6400, units = "px", dpi = 600)
  
  # Grey background — non-significant points as small grey dots
  p_grey <- ggplot() +
    geom_point(data = combined_org_grey %>% filter(!is_significant),
               aes(x = Soluble_FC, y = Insoluble_FC), size = 0.5, color = "gray60", alpha = 0.4) +
    geom_point(data = combined_org_grey %>% filter(is_significant),
               aes(x = Soluble_FC, y = Insoluble_FC, size = Size, color = Comparison), alpha = 0.4) +
    comp_colors +
    geom_text_repel(data = combined_org_grey %>% filter(is_significant),
                    aes(x = Soluble_FC, y = Insoluble_FC, label = Label, color = Comparison),
                    size = 5, fontface = "bold", segment.color = "grey50",
                    max.overlaps = Inf, nudge_x = 0.1, nudge_y = 0.1,
                    box.padding = 0.2, point.padding = 0.2, na.rm = TRUE) +
    scale_size_continuous(range = c(1,9), name = "P-Value Size (-log10)",
                          breaks = c(1.3,2,3,4,5), limit = c(1.3,8),
                          labels = c("1.30(p<0.05)","2","3","4","5")) +
    stat_poly_eq(data = combined_org_grey, aes(x = Soluble_FC, y = Insoluble_FC,
                                               label = paste(after_stat(rr.label))), rr.digits = 3,
                 parse = TRUE, color = "black", show.legend = FALSE, inherit.aes = FALSE) +
    labs(title   = paste0("MouseTMT ", full_name, ": Soluble FC vs. Insoluble FC"),
         x       = "Log2 Soluble fold change",
         y       = "Log2 Insoluble fold change",
         caption = "Colored: significant (p < 0.05). Grey: non-significant.") +
    scale_x_continuous(labels = scales::label_number(accuracy = 0.1)) +
    shared_theme + facet_wrap(~Comparison) +
    guides(color = guide_legend(override.aes = list(label = "")))
  
  print(p_grey)
  ggsave(paste0("mouseTMT_", organ_code, "_combined_facet_label_grey.pdf"),
         p_grey, width = 7200, height = 6400, units = "px", dpi = 600)
  
  return(list(combined_data = combined_org, combined_data_grey = combined_org_grey,
              ratio_data_OY = fc_OY, organ_code = organ_code))
}

# ============================================================
# 4. Run All Organs
# ============================================================

all_organs_data <- list()
for (organ_code in names(organ_files)) {
  all_organs_data[[organ_code]] <- process_organ_data(organ_code, organ_files[[organ_code]])
}

# ============================================================
# 5. Multi-Organ Combined Plots
# ============================================================

# Load and combine the saved CSVs (ensures consistent column structure)
load_combined_all <- function() {
  organ_full <- c(TA="Tibialis Anterior", He="Heart", CB="Cerebellum",
                  HC="Hippocampus", NC="Neocortex", So="Soleus",
                  Li="Liver", WAT="White Adipose Tissue")
  
  bind_rows(lapply(names(organ_full), function(code) {
    f <- paste0("combined_plot_data_mouseTMT_", code, ".csv")
    if (!file.exists(f)) return(NULL)
    read.csv(f) %>% mutate(Organ = organ_full[code], is_significant = !is.na(Size) & Size >= 1.3,
                           Organ_Name = Organ)
  })) %>%
    mutate(Comparison = factor(Comparison, levels = c("Old vs. Young", "Middle vs. Young", "Old vs. Middle")))
}

combined_all <- load_combined_all()
write.csv(combined_all, "combined_plot_data_mouseTMT_All.csv", row.names = FALSE)

organ_color_palette <- c(
  "Cerebellum"           = "#c7a6db", "Heart"             = "#c93b92",
  "Hippocampus"          = "#55397f", "Liver"             = "#4d9fdb",
  "Neocortex"            = "#8a68ca", "Soleus"            = "#a8192a",
  "Tibialis Anterior"    = "#e991b7", "White Adipose Tissue" = "#dfc41b"
)

multi_theme <- theme_minimal() +
  theme(axis.text.x   = element_text(size = 14, face = "bold"),
        axis.text.y   = element_text(size = 14, face = "bold"),
        legend.text   = element_text(size = 12, face = "italic"),
        legend.title  = element_text(size = 14, face = "bold"),
        plot.title    = element_text(size = 16, face = "bold"),
        axis.title.x  = element_text(size = 14, face = "bold"),
        axis.title.y  = element_text(size = 14, face = "bold"),
        strip.text    = element_text(size = 14, face = "bold"))

plot_data_clean <- combined_all %>%
  filter(!is.na(Soluble_FC), !is.na(Insoluble_FC), !is.na(Size),
         is.finite(Soluble_FC), is.finite(Insoluble_FC),
         Soluble_FC > -10 & Soluble_FC < 10,
         Insoluble_FC > -10 & Insoluble_FC < 10)

# Colored — significant only, colored by organ
p_whole_colored <- ggplot(plot_data_clean %>% filter(is_significant),
                          aes(x = Soluble_FC, y = Insoluble_FC, size = Size, color = Organ_Name)) +
  geom_point(alpha = 0.4) +
  scale_size_continuous(range = c(1,9), name = "P-Value Size (-log10)",
                        breaks = c(1.3,2,3,4,5), limit = c(1.3,6),
                        labels = c("1.30(p<0.05)","2","3","4","5")) +
  scale_color_manual(name = "Organ", values = organ_color_palette) +
  stat_poly_eq(data = plot_data_clean,
               aes(x = Soluble_FC, y = Insoluble_FC, label = paste(after_stat(rr.label))),
               rr.digits = 3, parse = TRUE, color = "black",
               show.legend = FALSE, inherit.aes = FALSE) +
  labs(title   = "MouseTMT Multi-Organ: Soluble FC vs. Insoluble FC",
       x       = "Log2 Soluble fold change",
       y       = "Log2 Insoluble fold change",
       caption = "Only significant proteins (p < 0.05) shown. R² from all data.") +
  scale_x_continuous(labels = scales::label_number(accuracy = 0.1)) +
  multi_theme + facet_wrap(~Comparison)

print(p_whole_colored)
ggsave("mouseTMT_whole_proteome_R_sig.pdf", p_whole_colored, width = 7200, height = 6400, units = "px", dpi = 600)

# Grey — all points; significant colored, non-significant grey
p_whole_grey <- ggplot() +
  geom_point(data = plot_data_clean %>% filter(!is_significant),
             aes(x = Soluble_FC, y = Insoluble_FC), size = 0.5, color = "gray60", alpha = 0.3) +
  geom_point(data = plot_data_clean %>% filter(is_significant),
             aes(x = Soluble_FC, y = Insoluble_FC, size = Size, color = Organ_Name), alpha = 0.5) +
  scale_size_continuous(range = c(1,9), name = "P-Value Size (-log10)",
                        breaks = c(1.3,2,3,4,5), limit = c(1.3,6),
                        labels = c("1.30(p<0.05)","2","3","4","5")) +
  scale_color_manual(name = "Organ", values = organ_color_palette) +
  stat_poly_eq(data = plot_data_clean,
               aes(x = Soluble_FC, y = Insoluble_FC, label = paste(after_stat(rr.label))),
               rr.digits = 3, parse = TRUE, color = "black",
               show.legend = FALSE, inherit.aes = FALSE) +
  labs(title   = "MouseTMT Multi-Organ: Soluble FC vs. Insoluble FC",
       x       = "Log2 Soluble fold change",
       y       = "Log2 Insoluble fold change",
       caption = "Colored: significant (p < 0.05). Grey: non-significant. R² from all data.") +
  scale_x_continuous(labels = scales::label_number(accuracy = 0.1)) +
  multi_theme + facet_wrap(~Comparison)

print(p_whole_grey)
ggsave("mouseTMT_whole_proteome_grey_R_all.pdf", p_whole_grey, width = 7200, height = 6400, units = "px", dpi = 600)

# ============================================================
# 6. Pearson Correlations: Soluble_FC vs. Ratio_FC
# ============================================================

# All proteins
correlations_all <- bind_rows(lapply(names(all_organs_data), function(code) {
  d <- all_organs_data[[code]]$combined_data %>%
    filter(!is.na(Soluble_FC), !is.na(Ratio_FC), is.finite(Soluble_FC), is.finite(Ratio_FC))
  
  bind_rows(lapply(unique(d$Comparison), function(comp) {
    sub <- d %>% filter(Comparison == comp)
    if (nrow(sub) <= 2) return(NULL)
    ct <- cor.test(sub$Soluble_FC, sub$Ratio_FC, method = "pearson")
    data.frame(Organ = code, Comparison = comp,
               Pearson_r = ct$estimate, p_value = ct$p.value, n = nrow(sub))
  }))
}))

write.csv(correlations_all, "pearson_correlations_soluble_vs_ratio.csv", row.names = FALSE)
cat("\nPearson correlations (all proteins):\n")
print(correlations_all)

# Significant proteins only (p < 0.05)
correlations_sig <- bind_rows(lapply(names(all_organs_data), function(code) {
  d <- all_organs_data[[code]]$combined_data %>%
    filter(!is.na(Soluble_FC), !is.na(Ratio_FC), is.finite(Soluble_FC), is.finite(Ratio_FC),
           !is.na(Size) & Size >= 1.3)
  
  bind_rows(lapply(unique(d$Comparison), function(comp) {
    sub <- d %>% filter(Comparison == comp)
    if (nrow(sub) <= 2) return(NULL)
    ct <- cor.test(sub$Soluble_FC, sub$Ratio_FC, method = "pearson")
    data.frame(Organ = code, Comparison = comp,
               Pearson_r = ct$estimate, p_value = ct$p.value, n_significant = nrow(sub))
  }))
}))

write.csv(correlations_sig, "pearson_correlations_soluble_vs_ratio_SIGNIFICANT_ONLY.csv", row.names = FALSE)
cat("\nPearson correlations (significant proteins only):\n")
print(correlations_sig)